name: Wan2.2-T2V-A14B
type: diffusion-wan
source: "https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir:<path>`.
low_noise_checkpoint: "low_noise_model"
high_noise_checkpoint: "high_noise_model"
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path:<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken

task: t2v

# copy from https://github.com/Wan-Video/Wan2.2/blob/main/wan/configs/wan_t2v_A14B.py
encoder:
  t5_checkpoint: "models_t5_umt5-xxl-enc-bf16.pth"
  t5_tokenizer: "google/umt5-xxl"
  t5_model: "umt5-xxl"
  text_len: 512

vae:
  checkpoint: "Wan2.1_VAE.pth"
  stride: [4, 8, 8]

transformer:  
  patch_size: [1, 2, 2]
  dim: 5120
  ffn_dim: 13824
  freq_dim: 256
  num_heads: 40
  num_layers: 40
  window_size: [-1, -1]
  qk_norm: True
  cross_attn_norm: True
  eps: 1e-6

sampler:
  sample_shift: 12.0
  sample_steps: 40
  boundary: [0.875]
  guidance_scale: [3.0, 4.0]
  num_train_timesteps: 1000
