# @package _global_

# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

hydra:
  callbacks:
    serve_config_rules:
      _target_: chitu.schemas.serve_config_rules.ServeConfigRules
