# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

num_reqs_list: [1] # eg: benchmark.num_reqs_list="[1,2,3,4,5]"
input_len: 128
output_len: 128
stop_with_eos: False # whether to stop with eos token
iters: 3
dataset: random # random or sharegpt
dataset_path: null # path to the dataset
debug_print: False # whether to print the first request output
profile_dir: null # path to the profile directory
profiler_with_stack: False